spring:
  data:
    mongodb:
      uri: mongodb+srv://Artha:Root@cluster0-b7ygr.mongodb.net/test?retryWrites=true&w=majority
      database: ArthaDB
      authentication-database: Admin
      
server:
  port: 2005   
      
